name: Deploy Blog
run-name: ${{ github.actor }} is deploying via GitHub Actions 🚀
on:
  push:
    branches:
      - 'main'
      - 'master'
jobs:
  Deploy-Blog:
    runs-on: ubuntu-24.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Cache node modules
        uses: actions/cache@v4
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: Resolve yarn cert issue
        run: yarn config set strict-ssl false
      - name: Install dependencies
        run: yarn install
      - name: Yarn Lock file
        run: cat yarn.lock
      - name: Build blog
        run: yarn build
      - name: Deploy blog to server
        id: deploy
        uses: Pendect/action-rsyncer@v1.1.0
        env:
          DEPLOY_KEY: ${{secrets.DeployKey}}
        with:
          flags: '-avzr --delete-after'
          options: ''
          ssh_options: '-T'
          src: 'public/'
          dest: ${{ format('root@{0}:~/blog/charlesfeng/blog/', secrets.DeployHost) }}
      - name: Display status from deploy
        run: echo "${{ steps.deploy.outputs.status }}"
      - name: Deploy error page to server
        id: deploy2
        uses: Pendect/action-rsyncer@v1.1.0
        env:
          DEPLOY_KEY: ${{secrets.DeployKey}}
        with:
          flags: '-avzr --delete-after'
          options: ''
          ssh_options: '-T'
          src: 'defaulterror/'
          dest: ${{ format('root@{0}:/data/charlesfeng/defaulterror/', secrets.DeployHost) }}
      - name: Display status from deploy error page
        run: echo "${{ steps.deploy2.outputs.status }}"