name: Deploy Blog
run-name: ${{ github.actor }} is deploying via GitHub Actions 🚀

on:
  push:
    branches:
      - 'main'
      - 'master'

permissions:
  contents: read # access to check out code and install dependencies by action setup-node

jobs:
  Deploy-Blog:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'
      - name: Resolve yarn cert issue
        run: yarn config set strict-ssl false
      - name: Install dependencies
        run: yarn install --frozen-lockfile # optional, --immutable
      - name: Build blog
        run: yarn build
      - name: Deploy blog to server
        id: deploy
        uses: Pendect/action-rsyncer@v2.0.0
        env:
          DEPLOY_KEY: ${{secrets.DeployKey}}
        with:
          flags: '-avzr --delete-after'
          options: ''
          ssh_options: ''
          src: 'public/'
          dest: ${{ format('root@{0}:/data/charlesfeng/blog/', secrets.DeployHost) }}
      - name: Display status from deploy
        run: echo "${{ steps.deploy.outputs.status }}"
      - name: Deploy error page to server
        id: deploy2
        uses: Pendect/action-rsyncer@v2.0.0
        env:
          DEPLOY_KEY: ${{secrets.DeployKey}}
        with:
          flags: '-avzr --delete-after'
          options: ''
          ssh_options: ''
          src: 'defaulterror/'
          dest: ${{ format('root@{0}:/data/charlesfeng/defaulterror/', secrets.DeployHost) }}
      - name: Display status from deploy error page
        run: echo "${{ steps.deploy2.outputs.status }}"